### ISSUE TITLE
Error: technology string must contain two colons (:), none found: "10XATAC"

### ISSUE THREAD

**Issue by tdfair** [pachterlab/BGP_2023#1]
Hi, 

Thanks for adding 10X ATAC-seq support to kb, I'm trying a command similar to this one (kb_python 0.27.3 installed): 

!kb count \
-i peaks.idx \
-g t2g.txt \
-x 10xATAC \
-o out \
-w 737K-cratac-v1.txt \
-t 2 \
--h5ad \
CB.fastq.gz R1.fastq.gz R2.fastq.gz

which raises the error 'technology string must contain two colons (:), none found: "10XATAC"'

Is there a publicly available version of kb_python (or kallisto) that supports this technology? 

Many thanks!

**Comment by sbooeshaghi** [comment]
Hi Tyler- thanks for the question. What I recommend is passing a custom technology string to the `-x` option in a manner that specifies the barcode and reads. This would look like

`0,0,16:-1,-1,-1:1,0,0,2,0,0`

For more information about the technology string see: https://pachterlab.github.io/kallisto/manual

I hope that helps!
